"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PhotoOrganizer.py']
DATA_FILES = ['AppUI.ui','Processed.ui','processing.ui','splash.ui']
OPTIONS = {
    'iconfile':'icon.ico',
    'plist': {'CFBundleShortVersionString':'0.1.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
